version: "3.5"

services:
  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/usr/src/app
      - ./.env:/usr/src/app/.env
    environment:
      - DATABASE_URL= 'postgresql://myuser:mypassword@db:5432/postgres'
    ports:
      - "8002:8002"
    expose:
      - 8002

  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 10

volumes:
  postgres_data:
